### ISSUE TITLE
File Strcture is wired

### ISSUE THREAD

**Issue by HsunGong** [shsjxzh/ACM-DB#3] opened 2020-03-25 06:37 UTC
Should be like:

- src
   - main
      - java
        - xxx
   - test
      - java
        - xxx

####################################

**But** your files are provided like 

- src
    - java
        - xxx
 - test
      - xxx

**Comment by shsjxzh** [comment] 2020-03-25 08:26
Thank you for your comments! Yes, it is somewhat wired compared with the general java projects. However, since many students have already downloaded and are working on this projects, and it is not a bug that need to be fixed, I decide not to change that file structure. But your suggestion is still valuable and we will take it into consideration next time we assign this project. Thanks a lot!

**Closed** 2020-03-31 16:30 UTC
